# Generated by Django 2.2 on 2019-09-07 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('family', models.CharField(max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cache', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('family', models.CharField(max_length=64)),
                ('chip', models.CharField(max_length=64)),
                ('vram', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('motherboard', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('Type', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('protocol', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
                ('connector', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcconfig.CPU')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcconfig.GPU')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcconfig.Motherboard')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcconfig.RAM')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcconfig.Storage')),
            ],
        ),
    ]
